#!/usr/bin/perl -w

=head1 NAME

mBuilder - Build ffmpeg commandline string to produce a video mosaic

=head1 SYNOPSIS

 mBuilder [options] configuration_file 

=head1 OPTIONS

 -h         show this help
 -c         only validate config file

=head1 DESCRIPTION

mBuilder uses input file in YAML format and generates output string fir ffmpeg to 
generate such an output.

 If no configuration file is found, mBuilder will use mosaic.yaml

Please install:
 libsmart-comments-perl libbareword-filehandles-perl libindirect-perl libmultidimensional-perl libstrictures-perl liblog-log4perl-perl libmoo-perl
 libimage-magick-perl

=cut

=head1 AUTHOR

Copyright (C) Bojan Ramsak 2019

All rights reserved

=cut

use 5.010;
use warnings;
use strict;
use utf8;
use Pod::Usage;
use Getopt::Std;
use lib './lib/';
use Mosaic;
use YAML::XS;
use Try::Tiny;
use Smart::Comments;
use open qw ( :std :encoding(UTF-8));

our $VERSION = '0.11';

my %args;

getopts( "hc", \%args );

say("mBuilder - ver. $VERSION Copyright 2019 Bojan Ramšak");

pod2usage(
    -verbose  => 99,
    -exitval  => 0,
    -sections => "SYNOPSIS|OPTIONS|DESCRIPTION"
    )
    if exists $args{h};

my $configFile = shift(@ARGV) // "mosaic.yaml";

### using configfile: $configFile

my $app = Mosaic->new( configFile => $configFile );

if ( $app->compileConfig() ) {
    say("Configuration invalid");
    exit(1);
}

if ( exists $args{c} ) {

    # just validate
    exit;
} else {
    my $line = $app->buildCmd();

    # Zapis v FFmpeg file
    my $mosaicFFmpeg = 'mosaic_FFmpeg.sh';
    open( my $fh, '>', $mosaicFFmpeg );
    print( $fh "#!/bin/bash\n" );
    print( $fh "".$line . "\n" );
    close($fh);

    say $app->buildTlay();
    exit;
} ## end else [ if ( exists $args{c} )]
